### ISSUE TITLE
Can‘t get credential with cli.js

### ISSUE THREAD

**Issue by Kohle81** [mag911/HomeBridge-AppleTV_as_an_Accessory#1]
Hi,
thanks for this plugin.

If I try 

/usr/local/lib/node_modules/homebridge-appletv-now-playing $ node .\bin/cli.js

there is an issue.

Could you help me, please?

**Comment by mag911** [comment]
Hi @Kohle81 
I'm flattered that you arrived at my plugin only half a day after I copied it in there! Just FYI, my plugin was copied from Kurt Warwick's published plugin - "Homebridge Appletv Now Playing". I've copied it so that I can do some additional development, fix the issues I'm having with it, and then publish it as a new variant.
That said, let me try and assist you.
Firstly, is your issue with actually launching the cli? Do you get the cli functioning? Or, do you get the cli but you can't get the credentials? I assume you're having trouble with launching the cli. Because I only copied the plugin 14 hours ago, I can't help at the moment with a non-functioning cli, as I have issues myself with getting the plugin to load under Homebridge.
However, if your goal is to get credentials to pair with your Apple TV, then maybe I can help.
From your Homebridge page, launch a 'Terminal' session.
Check & update Python to the latest supported version: ```python --version```
As far as I know, it should say ```Python 3.9.2```
Check & update pip, Python's package manager: ```pip --version```
As far as I know, it should say ```pip 20.3.4```
After checking those two, install pyatv with pip: ```pip install pyatv```
When you're happy with your installation of pyatv, try issuing the command ```atvremote scan```
If everything is going ok for you, now try and get the credentials with:
```atvremote --id <id> --protocol airplay pair```
All going well, your Apple TV should've just prompted you on-screen with a PIN verification code. Type that in you'll get a very long character string that is your credentials.
I need to leave it there because that's all I can help with for now.
😁👍🏼

**Comment by mag911** [comment]
Issue appears closed.
